---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: nixie-blue
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - install-kde-rounded.sh

  - type: dnf
    repos:
      nonfree: rpmfusion
      copr:
        - imput/helium
        - deltacopy/darkly
    install:
      packages:
        # Codecs
        - ffmpeg
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-ugly
        - mesa-va-drivers-freeworld
        - mesa-va-drivers-freeworld.i686

        # Mutlimedia
        - celluloid
        - gwenview
        - helium-bin
        - steam

        # Themeing
        - adw-gtk3-theme
        - darkly
        - elementary-icon-theme
        - papirus-icon-theme

        # Utilities
        - distrobox
        - gnome-calculator
        - gnome-disk-utility
        - input-remapper
        - nix

        # Virtualization
        - libvirt-daemon
        - libvirt-daemon-config-network
        - libvirt-daemon-driver-qemu
        - qemu-kvm
        - virt-manager
    remove:
      packages:
        - ffmpeg-free
        - filelight
        - firefox
        - firefox-langpacks
        - kde-partitionmanager
        - plasma-discover
        - plasma-discover-flatpak
        - plasma-discover-kns
        - plasma-discover-notifier
        - plasma-discover-rpm-ostree

  # - type: script
  #   scripts:
  #     - aurora-codecs.sh

  - type: systemd
    system:
      enabled:
        - input-remapper.service
        - nix.mount
        - nix-store-init.service
        - nix-daemon.service
        - nix-maintenance.timer
        - rpm-ostreed-automatic.timer
        - virtqemud.socket
        - virtnetworkd.socket

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false
        install:
          - io.github.flattool.Warehouse

  - type: os-release
    properties:
      ID: nixie_blue
      NAME: NixieBlue
      PRETTY_NAME: Nixie Blue

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
