---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: nixie-blue
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - install-kde-rounded.sh

  - type: dnf
    repos:
      files:
        - https://negativo17.org/repos/fedora-steam.repo
      copr:
        - imput/helium
        - deltacopy/darkly
    install:
      packages:
        - darkly
        - distrobox
        - gnome-disk-utility
        - helium-bin
        - input-remapper
        - nix
        - papirus-icon-theme
        - steam
    remove:
      packages:
        - filelight
        - firefox
        - firefox-langpacks
        - kde-partitionmanager
        - plasma-discover
        - plasma-discover-flatpak
        - plasma-discover-kns
        - plasma-discover-notifier
        - plasma-discover-rpm-ostree

  - type: script
    scripts:
      - aurora-codecs.sh
      - install-megasync.sh

  - type: systemd
    system:
      enabled:
        - nix.mount
        - nix-store-init.service
        - nix-daemon.service
        - nix-maintenance.timer
        - input-remapper.service
        - rpm-ostreed-automatic.timer

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false
        install:
          - io.github.flattool.Warehouse

  - type: os-release
    properties:
      ID: nixie_blue
      NAME: NixieBlue
      PRETTY_NAME: Nixie Blue

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
